// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ophhpevvaanvtnyncwgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9waGhwZXZ2YWFudnRueW5jd2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDQ4ODEsImV4cCI6MjA3MTk4MDg4MX0.KNyeNpUob-DGM2ujqMRo1b4QjYX8e8mTS7qVfjM56GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});